services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    PlantUmlBundle\Controller\Admin\PlantUmlController:
        tags: ['controller.service_arguments']
