plantuml_admin_generate:
    path: /admin/plantuml/generate
    defaults: { _controller: PlantUmlBundle:Admin\PlantUml:generate }

plantuml_admin_config_list:
    path: /admin/plantuml/config_list
    defaults: { _controller: PlantUmlBundle:Admin\PlantUml:listConfig }

plantuml_admin_config_get:
    path: /admin/plantuml/config_get
    defaults: { _controller: PlantUmlBundle:Admin\PlantUml:getConfig }

plantuml_admin_config_create:
    path: /admin/plantuml/config_create
    defaults: { _controller: PlantUmlBundle:Admin\PlantUml:createConfig }

plantuml_admin_config_delete:
    path: /admin/plantuml/config_delete
    defaults: { _controller: PlantUmlBundle:Admin\PlantUml:deleteConfig }

plantuml_admin_config_save:
    path: /admin/plantuml/config_save
    defaults: { _controller: PlantUmlBundle:Admin\PlantUml:saveConfig }

plantuml_admin_templates_list:
    path: /admin/plantuml/templates_list
    defaults: { _controller: PlantUmlBundle:Admin\PlantUml:listTemplates }
